# Site settings
title: Patrice S
description:
# url: "localhost:3000" #  TODO

# User settings
username: Patrice S
user_title: Software Developer
email: patrice.salathe@gmail.com
github_username:  onionpsy
stack_user_id: 1173117

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
